name: Build Docker Images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: current
        arguments: buildAndPushAllImages -PDOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }} -PDOCKERHUB_PASSWORD=${{ secrets.DOCKERHUB_PASSWORD }} -PIMAGE_TAG=${{ github.sha }}
  deploy:
    name: Deploy
    if: github.ref == 'refs/heads/main'
    needs: [ build ]
    runs-on: ubuntu-latest
    
    steps:
      - name: Set the Kubernetes context
        uses: azure/k8s-set-context@v2
        with:
          method: service-account
          k8s-url: https://130.162.226.216:16443
          k8s-secret: ${{ secrets.KUBERNETES_SECRET }}

      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Deploy to the Kubernetes cluster
        uses: azure/k8s-deploy@v1
        with:
          namespace: cd-thesis
          manifests: |
            k8s/thesis.yaml
          strategy: blue-green
          route-method: ingress
          images: |
            v3ro/thesis-one:${{ github.sha }}
            v3ro/thesis-two:${{ github.sha }}
            v3ro/thesis-three:${{ github.sha }}
            v3ro/thesis-four:${{ github.sha }}
            v3ro/thesis-five:${{ github.sha }}
