name: Build Docker Images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: buildAllImages
        
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Push ThesisOne
      run: docker image push ${{ secrets.DOCKERHUB_USERNAME }}/thesis-one:latest

    - name: Push ThesisTwo
      run: docker image push ${{ secrets.DOCKERHUB_USERNAME }}/thesis-two:latest
      
    - name: Push ThesisThree
      run: docker image push ${{ secrets.DOCKERHUB_USERNAME }}/thesis-three:latest
      
    - name: Push ThesisFour
      run: docker image push ${{ secrets.DOCKERHUB_USERNAME }}/thesis-four:latest
      
    - name: Push ThesisFive
      run: docker image push ${{ secrets.DOCKERHUB_USERNAME }}/thesis-five:latest
